#!/bin/bash
set -e

################
# Constants
################

HIPACHE_CONFIG_PATH=/etc/hipache/config.json


##############################
# Configuration variables
##############################

#-------------
# Hipache
#-------------

HIPACHE_HTTP_PORT=${HIPACHE_HTTP_PORT:-80}
HIPACHE_HTTPS_PORT=${HIPACHE_HTTPS_PORT:-443}
HIPACHE_NUM_WORKERS=${HIPACHE_NUM_WORKERS:-10}
HIPACHE_MAX_SOCKETS=${HIPACHE_MAX_SOCKETS:-100}
HIPACHE_DEAD_BACKEND_TTL=${HIPACHE_DEAD_BACKEND_TTL:-30}
HIPACHE_TCP_TIMEOUT=${HIPACHE_TCP_TIMEOUT:-30}
HIPACHE_RETRY_ON_ERROR=${HIPACHE_RETRY_ON_ERROR:-3}
HIPACHE_DEAD_BACKEND_ON_500=${HIPACHE_DEAD_BACKEND_ON_500:-true}
HIPACHE_HTTP_KEEP_ALIVE=${HIPACHE_HTTP_KEEP_ALIVE:-false}

#-----------
# Redis
#-----------

# Look for environment variables first
REDIS_HOST=${REDIS_HOST:-}
REDIS_PORT=${REDIS_PORT:-}

# Use linked redis container if present
if [ -n "${REDISIO_PORT_6379_TCP_ADDR}" ]; then
    REDIS_HOST=${REDIS_HOST:-${REDISIO_PORT_6379_TCP_ADDR}}
    REDIS_PORT=${REDIS_PORT:-${REDISIO_PORT_6379_TCP_PORT}}
fi

if [ -z "$REDIS_HOST" ]; then
    echo "ERROR! You must supply a URL to a redis host or link a redis " \
         "container." 1>&2
    exit -1
fi

# Fallback to default redis port
REDIS_PORT=${REDIS_PORT:-6379}


##############################
# Configuration templates
##############################

#--------------------
# Copy templates
#--------------------

# Hipache
mkdir -p /etc/hipache
cp /app/config/hipache.config.json $HIPACHE_CONFIG_PATH


#--------------------------------
# Replace template variables
#--------------------------------

# Hipache

sed 's/{{HIPACHE_HTTP_PORT}}/'"${HIPACHE_HTTP_PORT}"'/g' \
    -i $HIPACHE_CONFIG_PATH

sed 's/{{HIPACHE_HTTPS_PORT}}/'"${HIPACHE_HTTPS_PORT}"'/g' \
    -i $HIPACHE_CONFIG_PATH

sed 's/{{HIPACHE_NUM_WORKERS}}/'"${HIPACHE_NUM_WORKERS}"'/g' \
    -i $HIPACHE_CONFIG_PATH

sed 's/{{HIPACHE_MAX_SOCKETS}}/'"${HIPACHE_MAX_SOCKETS}"'/g' \
    -i $HIPACHE_CONFIG_PATH

sed 's/{{HIPACHE_DEAD_BACKEND_TTL}}/'"${HIPACHE_DEAD_BACKEND_TTL}"'/g' \
    -i $HIPACHE_CONFIG_PATH

sed 's/{{HIPACHE_TCP_TIMEOUT}}/'"${HIPACHE_TCP_TIMEOUT}"'/g' \
    -i $HIPACHE_CONFIG_PATH

sed 's/{{HIPACHE_RETRY_ON_ERROR}}/'"${HIPACHE_RETRY_ON_ERROR}"'/g' \
    -i $HIPACHE_CONFIG_PATH

sed 's/{{HIPACHE_DEAD_BACKEND_ON_500}}/'"${HIPACHE_DEAD_BACKEND_ON_500}"'/g' \
    -i $HIPACHE_CONFIG_PATH

sed 's/{{HIPACHE_HTTP_KEEP_ALIVE}}/'"${HIPACHE_HTTP_KEEP_ALIVE}"'/g' \
    -i $HIPACHE_CONFIG_PATH

# Redis

sed 's/{{REDIS_HOST}}/'"${REDIS_HOST}"'/g' \
    -i $HIPACHE_CONFIG_PATH

sed 's/{{REDIS_PORT}}/'"${REDIS_PORT}"'/g' \
    -i $HIPACHE_CONFIG_PATH


########################
# Application start
########################

/usr/bin/hipache -c $HIPACHE_CONFIG_PATH
